### ISSUE TITLE
ERORR . ALL PROXY REMOVE

### ISSUE THREAD

**Issue by 0xsiwant** [Solana0x/GrassNode#2]
all proxy remove , and that valid proxy

**Comment by rubnx** [comment]
Same here. I added 200 proxies and the program deletes all of them in a few minutes.

**Comment by Solana0x** [comment]
Yes add socks5 manually infront of every proxy address also if you wana run 200 proxy for your grass account add atleast 2000 proxy in the txt file because while mining sometimes some proxy goes dead or gives error and my bot due to error handling removes them from the list ! 

So dead proxy are removed and its refreshed with new proxy so that there is no loss in bandwidth with dead proxies ! and i have made major changes in the code kindly install new version updated code ! thanks :)

**Comment by Solana0x** [comment]
Solved
